jaffle_shop:
  outputs:
    dev:
      dataset: jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/gretar/bigquery_key_files/ds-group-gretar-ac72695bf985.json
      location: US
      method: service-account
      priority: interactive
      project: ds-group-gretar
      threads: 1
      type: bigquery
  target: dev
