globals:
    customer_id: 123456
    target_date: '2021-06-01'
    client_name: 'Gretar Atli Gretarsson'

parameters:
    train_fraction: 0.9
    random_state: 8 
    target_column: 'species'

catalog:
    example_iris_data:
        type: pandas.CSVDataSet
        filepath: 'data/01_raw/iris_testing.csv'

