name: stat-rethink-pymc
channels:
- defaults
dependencies:
  - jupyter
  - mkl-service
  - seaborn
  - statsmodels
  - pip
  - pip:
     - "git+git://github.com/arviz-devs/arviz.git@main"
     - "git+git://github.com/pymc-devs/pymc.git@main"
